---
title: "tidy-tuesday_apr-03-19"
author: "Samuel Prohaska"
date: "4/3/2019"
output: html_document
---
```{r cache = TRUE}
library(tidyverse)
bike_traffic <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-04-02/bike_traffic.csv")
```

```{r}
# count NA in bike counter, by crossing
bike_na <- bike_traffic %>% 
    filter(is.na(bike_count) == TRUE) %>%
    group_by(crossing) %>%
    count() %>%
    rename(bike_na = n)

# count NA in ped counter, by crossing
df_na <- bike_traffic %>% 
    filter(is.na(ped_count) == TRUE) %>%
    group_by(crossing) %>%
    count() %>%
    rename(ped_na = n) %>% 
    full_join(bike_na, by = 'crossing') # join w/ bike data

# join with count of all observations
df_na <- bike_traffic %>% 
    group_by(crossing) %>%
    count() %>%
    full_join(df_na, by = 'crossing')

# calc NA frequency by counter and type (ped, bike)
df_na <- df_na %>% mutate(ped_na.perc = ped_na / n,
                          bike_na.perc = bike_na / n)

```
